Output "demo.gif"
Set FontSize 22
Set Width 1200
Set Height 800
Set Padding 20
Set Theme "Monokai Soda"

Set Shell powershell

# El servidor debe de estar escuchando.

Hide
Type "just run-client"
Enter
Sleep 4s
Show

Sleep 3s
Type "Evan"
Sleep 1s
Enter
Sleep 1.5ms
Type "3"
Enter
Sleep 2s
Type "Hello to everyone"
Enter
Sleep 2s
Type "This is a demo of the chat"
Enter
Sleep 2s
Escape
Sleep 1s
Type "c"
Sleep 2s
Type "Created Room"
Enter
Sleep 1s
Type "1"
Sleep 1
Down
Sleep 1
Enter
Sleep 2s
Type "This is another room"
Enter
Escape
Sleep 1s
Type "2"
Down
Sleep 1s
Enter
Sleep 2s
Type "This is a private room with Clara"
Sleep 1s
Enter
Escape
Sleep 2s
Type "q"

