name: Report

on:
  push:
    branches: [ "main" ]
    paths:
      - 'docs/report/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'docs/report/**'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Typst
        uses: typst-community/setup-typst@v5
        with:
          executable-name: typst-latest

      - name: Compile report
        run: just docs 

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: docs/report/main.pdf
